package org.example.firsthotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:08.696+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "FirstHotel", 
                  wsdlLocation = "FirstHotel.wsdl",
                  targetNamespace = "http://www.example.org/FirstHotel/") 
public class FirstHotel_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/FirstHotel/", "FirstHotel");
    public final static QName FirstHotelSOAP = new QName("http://www.example.org/FirstHotel/", "FirstHotelSOAP");
    static {
        URL url = null;
        try {
            url = new URL("FirstHotel.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FirstHotel_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "FirstHotel.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FirstHotel_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FirstHotel_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstHotel_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns FirstHotel
     */
    @WebEndpoint(name = "FirstHotelSOAP")
    public FirstHotel getFirstHotelSOAP() {
        return super.getPort(FirstHotelSOAP, FirstHotel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstHotel
     */
    @WebEndpoint(name = "FirstHotelSOAP")
    public FirstHotel getFirstHotelSOAP(WebServiceFeature... features) {
        return super.getPort(FirstHotelSOAP, FirstHotel.class, features);
    }

}
