
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.firsthotel;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:08.649+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "FirstHotel",
                      portName = "FirstHotelSOAP",
                      targetNamespace = "http://www.example.org/FirstHotel/",
                      wsdlLocation = "FirstHotel.wsdl",
                      endpointInterface = "org.example.firsthotel.FirstHotel")
                      
public class FirstHotelImpl implements FirstHotel {

    private static final Logger LOG = Logger.getLogger(FirstHotelImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.firsthotel.FirstHotel#makeReservation(java.lang.String  clientId ,)java.lang.String  hotelName ,)java.lang.String  hotelCity ,)int  days ,)int  guestNumber )*
     */
    public java.lang.String makeReservation(java.lang.String clientId,java.lang.String hotelName,java.lang.String hotelCity,int days,int guestNumber) { 
        LOG.info("Executing operation makeReservation");
        System.out.println(clientId);
        System.out.println(hotelName);
        System.out.println(hotelCity);
        System.out.println(days);
        System.out.println(guestNumber);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
