CREATE DATABASE `msee_sp3_lsa` DEFAULT CHARSET=utf8;

USE `msee_sp3_lsa` ;

CREATE TABLE `USER_ATTRIBUTES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `ATTR_KEY` varchar(255) NOT NULL,
  `ATTR_VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 ;

CREATE TABLE `USER_CREDENTIALS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ;

-- INSERT some sample data
-- Passwords are treated as clear text for the sake of development. A password encoder can be easily introduced
-- by supplying a PasswordEncoder to CAS.
INSERT INTO USER_CREDENTIALS (USERNAME, PASSWORD) VALUES ('demo', '1234');
INSERT INTO USER_CREDENTIALS (USERNAME, PASSWORD) VALUES ('guest', 'guest');

INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('demo','MSEE_Name', 'Charalampos Vassiliou');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('demo','MSEE_Organization', 'Singular Logic');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('demo','MSEE_Email', 'ep6@singularlogic.eu');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('demo','MSEE_Role', 'SiLo superuser');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('demo','MSEE_Role', 'MSEE admin');

INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('guest','MSEE_Name', 'Guest user');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('guest','MSEE_Organization', 'MSEE');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('guest','MSEE_Email', 'guest@msee-ip.eu');
INSERT INTO USER_ATTRIBUTES (USERNAME,ATTR_KEY, ATTR_VALUE) VALUES ('guest','MSEE_Role', 'guest');