//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 10:18:52 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL",
xmlns = { 
		@javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI ="http://www.omg.org/spec/BPMN/20100524/MODEL"),
        @javax.xml.bind.annotation.XmlNs(prefix = "bpmndi", namespaceURI ="http://www.omg.org/spec/BPMN/20100524/DI"), 
        @javax.xml.bind.annotation.XmlNs(prefix = "omgdc", namespaceURI = "http://www.omg.org/spec/DD/20100524/DC"),
        @javax.xml.bind.annotation.XmlNs(prefix = "omgdi", namespaceURI = "http://www.omg.org/spec/DD/20100524/DI"),
		@javax.xml.bind.annotation.XmlNs(prefix = "tns", namespaceURI = "http://www.bpmnwithactiviti.org"),
		@javax.xml.bind.annotation.XmlNs(prefix = "sales", namespaceURI = "http://ws.chapter11.bpmnwithactiviti.org/"),
		@javax.xml.bind.annotation.XmlNs(prefix = "activiti", namespaceURI = "http://activiti.org/bpmn"),
		@javax.xml.bind.annotation.XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),
		@javax.xml.bind.annotation.XmlNs(prefix = "seiplab", namespaceURI = "http://demo.seiplab.atosresearch.eu/"),
		@javax.xml.bind.annotation.XmlNs(prefix = "logdemo", namespaceURI = "http://logistic.example.org")
		
		

          },
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.atosresearch.seiplab.yourbpm.bpmn.standard;
