
package eu.atosresearch.seiplab.yourbpm.kb.businesslogic;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebN1ServicePortType", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebN1ServicePortType {


    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addRequirement")
    @Oneway
    @RequestWrapper(localName = "addRequirement", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddRequirement")
    public void addRequirement(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param operation
     * @param bpmnId
     * @param url
     */
    @WebMethod(action = "urn:selectService")
    @Oneway
    @RequestWrapper(localName = "selectService", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.SelectService")
    public void selectService(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "url", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String url,
        @WebParam(name = "operation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String operation);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addReference")
    @Oneway
    @RequestWrapper(localName = "addReference", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddReference")
    public void addReference(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addContextualInformation")
    @Oneway
    @RequestWrapper(localName = "addContextualInformation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddContextualInformation")
    public void addContextualInformation(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param bpmnId
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "urn:getSelectedService")
    @WebResult(targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
    @RequestWrapper(localName = "getSelectedService", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.GetSelectedService")
    @ResponseWrapper(localName = "getSelectedServiceResponse", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.GetSelectedServiceResponse")
    public List<String> getSelectedService(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addOutputMetadata")
    @Oneway
    @RequestWrapper(localName = "addOutputMetadata", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddOutputMetadata")
    public void addOutputMetadata(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addInputMetadata")
    @Oneway
    @RequestWrapper(localName = "addInputMetadata", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddInputMetadata")
    public void addInputMetadata(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param annotation
     * @param bpmnId
     * @param type
     */
    @WebMethod(action = "urn:deleteAnnotation")
    @Oneway
    @RequestWrapper(localName = "deleteAnnotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.DeleteAnnotation")
    public void deleteAnnotation(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "type", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String type,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param bpmnId
     * @param type
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "urn:retrieveAnnotationOf")
    @WebResult(targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
    @RequestWrapper(localName = "retrieveAnnotationOf", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.RetrieveAnnotationOf")
    @ResponseWrapper(localName = "retrieveAnnotationOfResponse", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.RetrieveAnnotationOfResponse")
    public List<String> retrieveAnnotationOf(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "type", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String type);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addNonFunctionalProperty")
    @Oneway
    @RequestWrapper(localName = "addNonFunctionalProperty", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddNonFunctionalProperty")
    public void addNonFunctionalProperty(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param bpmnId
     * @return
     *     returns java.util.List<eu.atosresearch.webn1.businesslogic.ArrayOfString>
     */
    @WebMethod(action = "urn:retrieveServicesOf")
    @WebResult(targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
    @RequestWrapper(localName = "retrieveServicesOf", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.RetrieveServicesOf")
    @ResponseWrapper(localName = "retrieveServicesOfResponse", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.RetrieveServicesOfResponse")
    public List<ArrayOfString> retrieveServicesOf(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addAnnotation")
    @Oneway
    @RequestWrapper(localName = "addAnnotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddAnnotation")
    public void addAnnotation(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

    /**
     * 
     * @param annotation
     * @param bpmnId
     */
    @WebMethod(action = "urn:addFuntionalClassification")
    @Oneway
    @RequestWrapper(localName = "addFuntionalClassification", targetNamespace = "http://businesslogic.webn1.atosresearch.eu", className = "eu.atosresearch.webn1.businesslogic.AddFuntionalClassification")
    public void addFuntionalClassification(
        @WebParam(name = "BPMN_id", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String bpmnId,
        @WebParam(name = "annotation", targetNamespace = "http://businesslogic.webn1.atosresearch.eu")
        String annotation);

}
