
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.aircongo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:17.852+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "AirCongo",
                      portName = "AirCongoSOAP",
                      targetNamespace = "http://www.example.org/AirCongo/",
                      wsdlLocation = "AirCongo.wsdl",
                      endpointInterface = "org.example.aircongo.AirCongo")
                      
public class AirCongoImpl implements AirCongo {

    private static final Logger LOG = Logger.getLogger(AirCongoImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.aircongo.AirCongo#search(java.lang.String  depCity ,)java.lang.String  arrivCity ,)java.lang.String  depDate ,)java.lang.String  arrivDate )*
     */
    public org.example.aircongo.Results search(java.lang.String depCity,java.lang.String arrivCity,java.lang.String depDate,java.lang.String arrivDate) { 
        LOG.info("Executing operation search");
        System.out.println(depCity);
        System.out.println(arrivCity);
        System.out.println(depDate);
        System.out.println(arrivDate);
        try {
            org.example.aircongo.Results _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
