package org.example.aircongo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:17.882+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.example.org/AirCongo/", name = "AirCongo")
@XmlSeeAlso({ObjectFactory.class})
public interface AirCongo {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "Search", targetNamespace = "http://www.example.org/AirCongo/", className = "org.example.aircongo.Search")
    @WebMethod(operationName = "Search", action = "http://atosresearch.eu/AirCongo/Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://www.example.org/AirCongo/", className = "org.example.aircongo.SearchResponse")
    public org.example.aircongo.Results search(
        @WebParam(name = "DepCity", targetNamespace = "")
        java.lang.String depCity,
        @WebParam(name = "ArrivCity", targetNamespace = "")
        java.lang.String arrivCity,
        @WebParam(name = "DepDate", targetNamespace = "")
        java.lang.String depDate,
        @WebParam(name = "ArrivDate", targetNamespace = "")
        java.lang.String arrivDate
    );
}
