package org.example.aircongo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:17.894+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "AirCongo", 
                  wsdlLocation = "AirCongo.wsdl",
                  targetNamespace = "http://www.example.org/AirCongo/") 
public class AirCongo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/AirCongo/", "AirCongo");
    public final static QName AirCongoSOAP = new QName("http://www.example.org/AirCongo/", "AirCongoSOAP");
    static {
        URL url = null;
        try {
            url = new URL("AirCongo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AirCongo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "AirCongo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AirCongo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AirCongo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirCongo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirCongo
     */
    @WebEndpoint(name = "AirCongoSOAP")
    public AirCongo getAirCongoSOAP() {
        return super.getPort(AirCongoSOAP, AirCongo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirCongo
     */
    @WebEndpoint(name = "AirCongoSOAP")
    public AirCongo getAirCongoSOAP(WebServiceFeature... features) {
        return super.getPort(AirCongoSOAP, AirCongo.class, features);
    }

}
