//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 12:43:24 PM GMT+01:00 
//


package eu.atosresearch.seiplab.yourbpm.bpmn.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}dataInput"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}dataOutput"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}inputSet"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}outputSet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataInput",
    "dataOutput",
    "inputSet",
    "outputSet"
})
@XmlRootElement(name = "ioSpecification")
public class IoSpecification {

    @XmlElement(required = true)
    protected DataInput dataInput;
    @XmlElement(required = true)
    protected DataOutput dataOutput;
    @XmlElement(required = true)
    protected InputSet inputSet;
    @XmlElement(required = true)
    protected OutputSet outputSet;

    /**
     * Gets the value of the dataInput property.
     * 
     * @return
     *     possible object is
     *     {@link DataInput }
     *     
     */
    public DataInput getDataInput() {
        return dataInput;
    }

    /**
     * Sets the value of the dataInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataInput }
     *     
     */
    public void setDataInput(DataInput value) {
        this.dataInput = value;
    }

    /**
     * Gets the value of the dataOutput property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutput }
     *     
     */
    public DataOutput getDataOutput() {
        return dataOutput;
    }

    /**
     * Sets the value of the dataOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutput }
     *     
     */
    public void setDataOutput(DataOutput value) {
        this.dataOutput = value;
    }

    /**
     * Gets the value of the inputSet property.
     * 
     * @return
     *     possible object is
     *     {@link InputSet }
     *     
     */
    public InputSet getInputSet() {
        return inputSet;
    }

    /**
     * Sets the value of the inputSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputSet }
     *     
     */
    public void setInputSet(InputSet value) {
        this.inputSet = value;
    }

    /**
     * Gets the value of the outputSet property.
     * 
     * @return
     *     possible object is
     *     {@link OutputSet }
     *     
     */
    public OutputSet getOutputSet() {
        return outputSet;
    }

    /**
     * Sets the value of the outputSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputSet }
     *     
     */
    public void setOutputSet(OutputSet value) {
        this.outputSet = value;
    }

}
