//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 12:43:24 PM GMT+01:00 
//


package eu.atosresearch.seiplab.yourbpm.bpmn.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.atosresearch.webn1.bpmn.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _To_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "to");
    private final static QName _DataOutputRefs_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutputRefs");
    private final static QName _OutMessageRef_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "outMessageRef");
    private final static QName _InMessageRef_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "inMessageRef");
    private final static QName _SourceRef_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "sourceRef");
    private final static QName _From_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "from");
    private final static QName _TargetRef_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "targetRef");
    private final static QName _DataInputRefs_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInputRefs");
    private final static QName _Transformation_QNAME = new QName("http://www.omg.org/spec/BPMN/20100524/MODEL", "transformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.atosresearch.webn1.bpmn.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataOutputAssociation }
     * 
     */
    public DataOutputAssociation createDataOutputAssociation() {
        return new DataOutputAssociation();
    }

    /**
     * Create an instance of {@link SequenceFlow }
     * 
     */
    public SequenceFlow createSequenceFlow() {
        return new SequenceFlow();
    }

    /**
     * Create an instance of {@link InputSet }
     * 
     */
    public InputSet createInputSet() {
        return new InputSet();
    }

    /**
     * Create an instance of {@link ServiceTask }
     * 
     */
    public ServiceTask createServiceTask() {
        return new ServiceTask();
    }

    /**
     * Create an instance of {@link IoSpecification }
     * 
     */
    public IoSpecification createIoSpecification() {
        return new IoSpecification();
    }

    /**
     * Create an instance of {@link DataInput }
     * 
     */
    public DataInput createDataInput() {
        return new DataInput();
    }

    /**
     * Create an instance of {@link DataOutput }
     * 
     */
    public DataOutput createDataOutput() {
        return new DataOutput();
    }

    /**
     * Create an instance of {@link OutputSet }
     * 
     */
    public OutputSet createOutputSet() {
        return new OutputSet();
    }

    /**
     * Create an instance of {@link DataInputAssociation }
     * 
     */
    public DataInputAssociation createDataInputAssociation() {
        return new DataInputAssociation();
    }

    /**
     * Create an instance of {@link Assignment }
     * 
     */
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link ReceiveTask }
     * 
     */
    public ReceiveTask createReceiveTask() {
        return new ReceiveTask();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link ItemDefinition }
     * 
     */
    public ItemDefinition createItemDefinition() {
        return new ItemDefinition();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link StartEvent }
     * 
     */
    public StartEvent createStartEvent() {
        return new StartEvent();
    }

    /**
     * Create an instance of {@link EndEvent }
     * 
     */
    public EndEvent createEndEvent() {
        return new EndEvent();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "to")
    public JAXBElement<String> createTo(String value) {
        return new JAXBElement<String>(_To_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "dataOutputRefs")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataOutputRefs(String value) {
        return new JAXBElement<String>(_DataOutputRefs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "outMessageRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutMessageRef(String value) {
        return new JAXBElement<String>(_OutMessageRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "inMessageRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInMessageRef(String value) {
        return new JAXBElement<String>(_InMessageRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "sourceRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSourceRef(String value) {
        return new JAXBElement<String>(_SourceRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "from")
    public JAXBElement<String> createFrom(String value) {
        return new JAXBElement<String>(_From_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "targetRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTargetRef(String value) {
        return new JAXBElement<String>(_TargetRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "dataInputRefs")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataInputRefs(String value) {
        return new JAXBElement<String>(_DataInputRefs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", name = "transformation")
    public JAXBElement<String> createTransformation(String value) {
        return new JAXBElement<String>(_Transformation_QNAME, String.class, null, value);
    }

}
