//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 12:43:24 PM GMT+01:00 
//


package eu.atosresearch.seiplab.yourbpm.bpmn.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}ioSpecification"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}dataInputAssociation"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}dataOutputAssociation"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="operationRef" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ioSpecification",
    "dataInputAssociation",
    "dataOutputAssociation"
})
@XmlRootElement(name = "serviceTask")
public class ServiceTask {

    @XmlElement(required = true)
    protected IoSpecification ioSpecification;
    @XmlElement(required = true)
    protected DataInputAssociation dataInputAssociation;
    @XmlElement(required = true)
    protected DataOutputAssociation dataOutputAssociation;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "implementation", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String implementation;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "operationRef", required = true)
//    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NOTATION")
    protected QName operationRef;
    @XmlAttribute(name = "completionQuantity", required = false)
    @XmlSchemaType(name = "anySimpleType")
    protected String completionQuantity;

    public String getCompletionQuantity() {
        return completionQuantity;
    }

    public void setCompletionQuantity(String completionQuantity) {
        this.completionQuantity = completionQuantity;
    }

    public String getIsForCompensation() {
        return isForCompensation;
    }

    public void setIsForCompensation(String isForCompensation) {
        this.isForCompensation = isForCompensation;
    }

    public String getStartQuantity() {
        return startQuantity;
    }

    public void setStartQuantity(String startQuantity) {
        this.startQuantity = startQuantity;
    }
    @XmlAttribute(name = "startQuantity", required = false)
    @XmlSchemaType(name = "anySimpleType")
    protected String startQuantity;
    @XmlAttribute(name = "isForCompensation", required = false)
    @XmlSchemaType(name = "anySimpleType")
    protected String isForCompensation;
        
    
    /**
     * Gets the value of the ioSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link IoSpecification }
     *     
     */
    public IoSpecification getIoSpecification() {
        return ioSpecification;
    }

    /**
     * Sets the value of the ioSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link IoSpecification }
     *     
     */
    public void setIoSpecification(IoSpecification value) {
        this.ioSpecification = value;
    }

    /**
     * Gets the value of the dataInputAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link DataInputAssociation }
     *     
     */
    public DataInputAssociation getDataInputAssociation() {
        return dataInputAssociation;
    }

    /**
     * Sets the value of the dataInputAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataInputAssociation }
     *     
     */
    public void setDataInputAssociation(DataInputAssociation value) {
        this.dataInputAssociation = value;
    }

    /**
     * Gets the value of the dataOutputAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutputAssociation }
     *     
     */
    public DataOutputAssociation getDataOutputAssociation() {
        return dataOutputAssociation;
    }

    /**
     * Sets the value of the dataOutputAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutputAssociation }
     *     
     */
    public void setDataOutputAssociation(DataOutputAssociation value) {
        this.dataOutputAssociation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the operationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public QName getOperationRef() {
        return operationRef;
    }

    /**
     * Sets the value of the operationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationRef(QName value) {
        this.operationRef = value;
    }
    public void setOperationRef(String value) {
        this.operationRef = new QName(value);
    }
}
