
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.brusselairlines;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:04.577+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "BrusselAirlines",
                      portName = "BrusselAirlinesSOAP",
                      targetNamespace = "http://www.example.org/BrusselAirlines/",
                      wsdlLocation = "BrusselAirlines.wsdl",
                      endpointInterface = "org.example.brusselairlines.BrusselAirlines")
                      
public class BrusselAirlinesImpl implements BrusselAirlines {

    private static final Logger LOG = Logger.getLogger(BrusselAirlinesImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.brusselairlines.BrusselAirlines#searchFlights(org.example.brusselairlines.Flights  parameters )*
     */
    public org.example.brusselairlines.FlightsResponseType searchFlights(Flights parameters) { 
        LOG.info("Executing operation searchFlights");
        System.out.println(parameters);
        try {
            org.example.brusselairlines.FlightsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
