package org.example.brusselairlines;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:04.702+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "BrusselAirlines", 
                  wsdlLocation = "BrusselAirlines.wsdl",
                  targetNamespace = "http://www.example.org/BrusselAirlines/") 
public class BrusselAirlines_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/BrusselAirlines/", "BrusselAirlines");
    public final static QName BrusselAirlinesSOAP = new QName("http://www.example.org/BrusselAirlines/", "BrusselAirlinesSOAP");
    static {
        URL url = null;
        try {
            url = new URL("BrusselAirlines.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BrusselAirlines_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BrusselAirlines.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BrusselAirlines_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BrusselAirlines_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrusselAirlines_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BrusselAirlines
     */
    @WebEndpoint(name = "BrusselAirlinesSOAP")
    public BrusselAirlines getBrusselAirlinesSOAP() {
        return super.getPort(BrusselAirlinesSOAP, BrusselAirlines.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrusselAirlines
     */
    @WebEndpoint(name = "BrusselAirlinesSOAP")
    public BrusselAirlines getBrusselAirlinesSOAP(WebServiceFeature... features) {
        return super.getPort(BrusselAirlinesSOAP, BrusselAirlines.class, features);
    }

}
