
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.hostelworld;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:11.578+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "HostelWorld",
                      portName = "HostelWorldSOAP",
                      targetNamespace = "http://www.example.org/HostelWorld/",
                      wsdlLocation = "HostelWorld.wsdl",
                      endpointInterface = "org.example.hostelworld.HostelWorld")
                      
public class HostelWorldImpl implements HostelWorld {

    private static final Logger LOG = Logger.getLogger(HostelWorldImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.hostelworld.HostelWorld#book(java.lang.String  hotelName ,)java.lang.String  roomType ,)int  nights ,)java.lang.String  clientId )*
     */
    public java.lang.String book(java.lang.String hotelName,java.lang.String roomType,int nights,java.lang.String clientId) { 
        LOG.info("Executing operation book");
        System.out.println(hotelName);
        System.out.println(roomType);
        System.out.println(nights);
        System.out.println(clientId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
