package org.example.hostelworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-07-07T00:29:11.619+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "HostelWorld", 
                  wsdlLocation = "HostelWorld.wsdl",
                  targetNamespace = "http://www.example.org/HostelWorld/") 
public class HostelWorld_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/HostelWorld/", "HostelWorld");
    public final static QName HostelWorldSOAP = new QName("http://www.example.org/HostelWorld/", "HostelWorldSOAP");
    static {
        URL url = null;
        try {
            url = new URL("HostelWorld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HostelWorld_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "HostelWorld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HostelWorld_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HostelWorld_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HostelWorld_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HostelWorld
     */
    @WebEndpoint(name = "HostelWorldSOAP")
    public HostelWorld getHostelWorldSOAP() {
        return super.getPort(HostelWorldSOAP, HostelWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostelWorld
     */
    @WebEndpoint(name = "HostelWorldSOAP")
    public HostelWorld getHostelWorldSOAP(WebServiceFeature... features) {
        return super.getPort(HostelWorldSOAP, HostelWorld.class, features);
    }

}
